export { AITutorSection } from "./AITutorSection";
export { CTASection } from "./CTASection";
export { FeaturedCoursesSection } from "./FeaturedCoursesSection";
export { FeaturesSection } from "./FeaturesSection";
export { Footer } from "./Footer";
export { HeroSection } from "./HeroSection";
export { LearningPathsSection } from "./LearningPathsSection";
export { PricingPreviewSection } from "./PricingPreviewSection";
export { StatsSection } from "./StatsSection";
